name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      working-directory: ./Lukuvinkkikirjasto
      run: chmod +x gradlew
    - name: Checkstyle test
      working-directory: ./Lukuvinkkikirjasto
      run: ./gradlew checkstyleMain
    - name: Test with Gradle
      working-directory: ./Lukuvinkkikirjasto
      run: ./gradlew test
    
